# Generated by Django 5.1.1 on 2024-11-08 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_incident_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='happened_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='recieved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
