# Generated by Django 5.1.1 on 2024-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_incident_api', '0002_incidentreport_happened_at_incidentreport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='emergency_level',
            field=models.IntegerField(null=True),
        ),
    ]
