# Generated by Django 5.1.1 on 2024-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_incident_api', '0003_incidentreport_emergency_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='isResolved',
            new_name='is_resolved',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
